applications:

  my-frontend:
    repo: https://github.com/my/frontend.git
    branch: develop

  my-backend:
    repo: git@git.lr.net:my/backend.git
    branch: master
    options:
      - compose-service-name: my-backend-compose-service
        auto-start: false
