version: '2'
services:
  squid:
    container_name: squid
    build: ../scripts/docker/squid/
    ports:
      - 30128:3128
    volumes:
     - ../scripts/docker/squid/squid.conf:/etc/squid/squid.conf
