version: '2'
services:
  # Back-compat: So apps compose files dont need to care if its logstash or not, call this container logstash as well
  logstash:
    container_name: logstash
    build: ${PWD}/scripts/docker/logging
    volumes:
     - ${PWD}/logs:/log-dir
    ports:
      - "25826:25826"
    restart: on-failure
    